services:
#    jlam_cdn2015.example:
#        class: Jlam\Cdn2015Bundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]


#jlam_cdn2015.twig.safe_divide:
#        class: Jlam\Cdn2015Bundle\Twig\SafeDivideExtension
#        tags:
#            - { name: twig.extension }
